siteName: "🐠 pezware"
description: "Too early"
baseURL: ""
githubRepo: "Slow-Town-LLC-Internal/myflow"
GATrackingID: "G-8F14DZKGLE"
defaultOrder:
  - "Informations générales"
  - "Français"
  - "Musique"
