siteName: "Flowing doc"
description: "Very random and flowing docs"
baseURL: "/newdocs"
githubRepo: "Slow-Town-LLC-Internal/myflow"
defaultOrder:
  - "Informations générales"
  - "Français"
  - "Musique"
